"""empty message

Revision ID: b13073853bde
Revises: f7db6b6cfd44
Create Date: 2025-05-05 11:52:07.794468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b13073853bde'
down_revision = 'f7db6b6cfd44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('assembly_cost', sa.Float(), nullable=True),
    sa.Column('default_profit_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
